theme: jekyll-theme-slate
title: Reyhaneh Maktoufi
description: Science Communication Enthusiast, Researcher and Trainer <br/>
[**A**bout](http://reyhanehmaktoufi.com) &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;   [**R**esearch](https://reymaktoufi.github.io/Reyhaneh-Maktoufi/research.html) &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [**S**cience Communication](https://reymaktoufi.github.io/Reyhaneh-Maktoufi/science-communication.html) &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;   [**I**n Media](https://reymaktoufi.github.io/Reyhaneh-Maktoufi/in-media.html)
google_analytics: 91823788

